"""
VulnFlask — SECURED VERSION
===========================
All known vulnerabilities patched. Auto-generated by PowerDash AI.
"""
import os, hashlib, secrets, shlex, subprocess
from flask import Flask, request, render_template_string, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash
import sqlite3

app = Flask(__name__)
app.secret_key = os.environ.get("APP_SECRET_KEY", secrets.token_hex(32))

DB = "users.db"

def db():
    c = sqlite3.connect(DB)
    c.row_factory = sqlite3.Row
    return c

@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        u = request.form.get("username", "")
        p = request.form.get("password", "")
        with db() as c:
            row = c.execute("SELECT * FROM users WHERE username = ?", (u,)).fetchone()
        if row and check_password_hash(row["password_hash"], p):
            session["user"] = u
            return redirect(url_for("home"))
        return "Invalid credentials", 401
    return render_template_string('<form method="post">User: <input name="username"> Pass: <input name="password" type="password"><button>Login</button></form>')

@app.route("/register", methods=["POST"])
def register():
    u = request.form.get("username", "")
    p = request.form.get("password", "")
    if len(p) < 8:
        return "Password too short", 400
    h = generate_password_hash(p)  # uses pbkdf2:sha256
    with db() as c:
        c.execute("INSERT INTO users (username, password_hash) VALUES (?, ?)", (u, h))
        c.commit()
    return "Registered"

@app.route("/search")
def search():
    q = request.args.get("q", "")
    # Jinja2 auto-escapes — safe
    return render_template_string("<p>Searching for: {{q}}</p>", q=q)

@app.route("/ping")
def ping():
    host = request.args.get("host", "")
    # Strict whitelist: only hostnames/IPs
    if not host.replace(".", "").replace("-", "").isalnum():
        return "Invalid host", 400
    cmd = ["ping", "-c", "1", host]
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=5, shell=False)
        return f"<pre>{out.stdout}</pre>"
    except subprocess.TimeoutExpired:
        return "Timeout", 504

@app.route("/")
def home():
    return "VulnFlask (secured)"

if __name__ == "__main__":
    # Debug OFF, bind only loopback for safety
    app.run(host="127.0.0.1", port=5000, debug=False)
