@echo off
setlocal enabledelayedexpansion
 
:: =============================================================
::  DevSecOps Pipeline - Phase 1 Setup Script (Windows CMD)
::  Run this ONCE from the project root folder.
::  Requirements: Docker Desktop running, Python installed,
::                curl available (Windows 10+ has it built-in)
:: =============================================================
 
set DOJO_URL=http://localhost:8080
set DOJO_USER=marwan
set DOJO_PASS=marwan
set GITHUB_USER=BouzaabiaMr1
set REPO_NAME=devsecops-pipeline
 
echo.
echo ============================================
echo   DevSecOps Pipeline - Phase 1 Setup
echo ============================================
echo.
 
:: ── Step 1: Check Python is installed ────────────────────────
echo [1/6] Checking Python...
python --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not in PATH.
    echo         Download from https://python.org
    pause
    exit /b 1
)
for /f "tokens=*" %%i in ('python --version') do echo [OK] %%i
 
:: ── Step 2: Check curl is available ──────────────────────────
echo.
echo [2/6] Checking curl...
curl --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] curl not found. It should be built into Windows 10+.
    echo         Try: where curl
    pause
    exit /b 1
)
echo [OK] curl found
 
:: ── Step 3: Check DefectDojo is reachable ────────────────────
echo.
echo [3/6] Checking DefectDojo at %DOJO_URL% ...
curl -s -o nul -w "%%{http_code}" %DOJO_URL%/api/v2/users/ > tmp_http.txt 2>nul
set /p HTTP_CODE=<tmp_http.txt
del tmp_http.txt >nul 2>&1
 
if "%HTTP_CODE%"=="000" (
    echo [ERROR] Cannot reach DefectDojo at %DOJO_URL%
    echo         Make sure Docker Desktop is running.
    echo         Run: docker ps
    pause
    exit /b 1
)
echo [OK] DefectDojo is reachable ^(HTTP %HTTP_CODE%^)
 
:: ── Step 4: Get API token ─────────────────────────────────────
echo.
echo [4/6] Retrieving API key for user "%DOJO_USER%"...
 
curl -s -X POST "%DOJO_URL%/api/v2/api-token-auth/" ^
    -H "Content-Type: application/json" ^
    -d "{\"username\": \"%DOJO_USER%\", \"password\": \"%DOJO_PASS%\"}" ^
    -o tmp_token.json 2>nul
 
python -c "import json,sys; d=json.load(open('tmp_token.json')); print(d.get('token','ERROR'))" > tmp_key.txt 2>nul
set /p API_KEY=<tmp_key.txt
del tmp_token.json >nul 2>&1
del tmp_key.txt    >nul 2>&1
 
if "%API_KEY%"=="ERROR" (
    echo [ERROR] Could not retrieve API key.
    echo         Make sure admin/admin credentials are correct.
    echo         Or get it manually: %DOJO_URL%/api/key-v2
    pause
    exit /b 1
)
 
:: Show first 8 chars only for security
set KEY_PREVIEW=%API_KEY:~0,8%
echo [OK] API Key retrieved: %KEY_PREVIEW%...
 
:: ── Step 5: Save .env file ────────────────────────────────────
echo.
echo [5/6] Saving .env file...
 
(
    echo # DefectDojo Configuration
    echo # Generated by setup.bat - DO NOT commit this file
    echo DOJO_URL=%DOJO_URL%
    echo DOJO_API_KEY=%API_KEY%
    echo DOJO_PRODUCT=VulnFlask
) > .env
 
echo [OK] Saved to .env ^(already in .gitignore^)
 
:: ── Step 6: Create VulnFlask product in DefectDojo ───────────
echo.
echo [6/6] Creating "VulnFlask" product in DefectDojo...
 
curl -s -X POST "%DOJO_URL%/api/v2/products/" ^
    -H "Authorization: Token %API_KEY%" ^
    -H "Content-Type: application/json" ^
    -d "{\"name\": \"VulnFlask\", \"description\": \"Intentionally vulnerable Flask app - DevSecOps demo\", \"prod_type\": 1}" ^
    -o tmp_product.json 2>nul
 
python -c "import json; d=json.load(open('tmp_product.json')); print('Product ID:', d.get('id', d.get('message','check DefectDojo')))" 2>nul
del tmp_product.json >nul 2>&1
 
:: ── Final instructions ────────────────────────────────────────
echo.
echo ============================================
echo   Setup Complete!
echo ============================================
echo.
echo   Your API Key (add to GitHub Secrets):
echo.
echo   DOJO_API_KEY = %API_KEY%
echo   DOJO_URL     = %DOJO_URL%
echo.
echo   IMPORTANT - GitHub Actions cannot reach 127.0.0.1
echo   You need to expose DefectDojo via ngrok:
echo.
echo     1. Download ngrok: https://ngrok.com/download
echo     2. Run: ngrok http 8080
echo     3. Copy the https://xxxx.ngrok.io URL
echo     4. Use THAT as DOJO_URL in GitHub Secrets
echo.
echo   Next steps:
echo     git init
echo     git add .
echo     git commit -m "feat: DevSecOps pipeline Phase 1"
echo     git remote add origin https://github.com/YOUR_USERNAME/devsecops-pipeline.git
echo     git push -u origin main
echo.
pause